# -*- coding: utf-8 -*-
"""Silvia Ocaña M4 - 10 - Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C716gughr6hGnt_cVDnCQpKSBSYdRVrD
"""

import pandas as pd
import numpy as np

"""# Ejercicio 1

Obtener las primeras `3` filas de un objeto `DataFrame`.


"""

#Datos
nombre = ['Oliva', 'Daniela', 'Juan', 'Germán', 'Edward', 'Alex', 'Julio', 
          'Edgar', 'Angie', 'Irlesa']
puntaje = [11.5, 8, 15.5, np.nan, 8, 19, 13.5, np.nan, 8, 18]
intentos = [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
califico = ['Sí', 'No', 'Sí', 'No', 'No', 'Sí', 'Sí', 'No', 'No', 'Sí']

indices = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

jugadores = {'nombre': nombre, 'puntaje': puntaje, 'intentos': intentos, 
             'califico': califico}

df = pd.DataFrame(data=jugadores, index=indices)

df

#Solución, aquí tu respuesta
df[:3]
#df.head(3)
#df.iloc[list(range(0,3)),[1]]
#df.loc[["a","f"], ["puntuaje", "nombre"]]

"""# Ejercicio 2

Obtener las últimas `3` filas de un objeto `DataFrame`.


"""

#Datos
nombre = ['Oliva', 'Daniela', 'Juan', 'Germán', 'Edward', 'Alex', 'Julio', 
          'Edgar', 'Angie', 'Irlesa']
puntaje = [11.5, 8, 15.5, np.nan, 8, 19, 13.5, np.nan, 8, 18]
intentos = [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
califico = ['Sí', 'No', 'Sí', 'No', 'No', 'Sí', 'Sí', 'No', 'No', 'Sí']

indices = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

jugadores = {'nombre': nombre, 'puntaje': puntaje, 'intentos': intentos, 
             'califico': califico}

df = pd.DataFrame(data=jugadores, index=indices)

df

#Solución
df[-3:]
#df.tail(3)

"""# Ejercicio 3

Seleccionar las columnas ['nombre', 'califico'] de un objeto `DataFrame`.

"""

nombre = ['Oliva', 'Daniela', 'Juan', 'Germán', 'Edward', 'Alex', 'Julio', 
          'Edgar', 'Angie', 'Irlesa']
puntaje = [11.5, 8, 15.5, np.nan, 8, 19, 13.5, np.nan, 8, 18]
intentos = [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
califico = ['Sí', 'No', 'Sí', 'No', 'No', 'Sí', 'Sí', 'No', 'No', 'Sí']

indices = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

jugadores = {'nombre': nombre, 'puntaje': puntaje, 'intentos': intentos, 
             'califico': califico}

df = pd.DataFrame(data=jugadores, index=indices)

df

df[['nombre', 'califico']]
# df.loc[["a","f"], ["nombre","califico"]]

"""# Ejercicio 4

Comprobar si este objeto `DataFrame` está vacío con `empty`.


"""

df = pd.DataFrame({'X': []})

df.empty

"""# Ejercicio 5

Crear un objeto `DataFrame` a partir de objetos `Series`.


"""

#Partimos de dos series
nombres = pd.Series(['Edward', 'Germán', 'Daniela'])
edades = pd.Series([27, 23, 19])

#1. Metemos las series en un diccionario
dic = {'Nombre': nombres, 'Edad' : edades}
#2. Metemos el diccionario dentro de un dataframe
df = pd.DataFrame.from_dict(dic)
print(df, type(df))

"""# Ejercicio 6

Determinar los datos en un `DataFrame` que son nulos (NaN).


"""

nombres = ['Edward', 'Daniela', 'Germán']
edades = [5, 6, np.nan]
fecha_nacimiento = [pd.Timestamp('1990-01-03'), None, np.nan]

personas = {'nombre': nombres, 'edad': edades, 'fecha_nacimiento': fecha_nacimiento}

df = pd.DataFrame(data=personas)

df
df.isnull().sum()

"""# Ejercicio 7

Modificar un valor o entrada específico de un objeto `DataFrame` usando `loc`.


"""

datos = {'X': [1, 2, 3, 4, 5], 'Y': [5, 4, 3, 2, 1], 'Z': [2, 3, 5, 7, 11]}

indices = ['a', 'b', 'c', 'd', 'e']

df = pd.DataFrame(data=datos, index=indices)

df

# df.loc["d", "Z"] =8
# df
df.loc[["d"],["Z"]] = df.loc[["d"],["Z"]].replace(7,8)
df

"""# Ejercicio 8

Acceder a un valor o entrada específico de un objeto `DataFrame` usando `loc`.


"""

datos = {'X': [1, 2, 3, 4, 5], 'Y': [5, 4, 3, 2, 1], 'Z': [2, 3, 5, 7, 11]}

indices = ['a', 'b', 'c', 'd', 'e']

df = pd.DataFrame(data=datos, index=indices)

df

"""# Ejercicio 9

Sumar los valores de la columna intentos con `sum`.


"""

nombre = ['Oliva', 'Daniela', 'Juan', 'Germán', 'Edward', 'Alex', 'Julio', 
          'Edgar', 'Angie', 'Irlesa']
puntaje = [11.5, 8, 15.5, np.nan, 8, 19, 13.5, np.nan, 8, 18]
intentos = [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
califico = ['Sí', 'No', 'Sí', 'No', 'No', 'Sí', 'Sí', 'No', 'No', 'Sí']

indices = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

jugadores = {'nombre': nombre, 'puntaje': puntaje, 'intentos': intentos, 
             'califico': califico}

df = pd.DataFrame(data=jugadores, index=indices)

df

df['intentos'].sum()

"""# Ejercicio 10 (Opcional)

 Agregar una nueva fila a un objeto `DataFrame` por medio de `loc`.


"""

nombre = ['Oliva', 'Daniela', 'Juan', 'Germán', 'Edward', 'Alex', 'Julio', 
          'Edgar', 'Angie', 'Irlesa']
puntaje = [11.5, 8, 15.5, np.nan, 8, 19, 13.5, np.nan, 8, 18]
intentos = [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
califico = ['Sí', 'No', 'Sí', 'No', 'No', 'Sí', 'Sí', 'No', 'No', 'Sí']

indices = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

jugadores = {'nombre': nombre, 'puntaje': puntaje, 'intentos': intentos, 
             'califico': califico}

df = pd.DataFrame(data=jugadores, index=indices)

df

#list_row = ["Alberto", 0, 11, 'No']
df.loc['k'] = ["Alberto", 0, 11, 'No']
df

"""# Ejercicio 11

Eliminar una fila de un `DataFrame` con la función `drop`.


"""

nombre = ['Oliva', 'Daniela', 'Juan', 'Germán', 'Edward', 'Alex', 'Julio', 
          'Edgar', 'Angie', 'Irlesa']
puntaje = [11.5, 8, 15.5, np.nan, 8, 19, 13.5, np.nan, 8, 18]
intentos = [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
califico = ['Sí', 'No', 'Sí', 'No', 'No', 'Sí', 'Sí', 'No', 'No', 'Sí']

indices = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

jugadores = {'nombre': nombre, 'puntaje': puntaje, 'intentos': intentos, 
             'califico': califico}

df = pd.DataFrame(data=jugadores, index=indices)

df

df= df.drop(index= 'j')
#alternativa sin drop df= df[:-1][:]
df

"""# Ejercicio 12

Mostrar los n primeros y últimos registros de un objeto `DataFrame` con `head` y `tail`.


"""

datos_1 = list(range(1, 101))
datos_2 = list(range(1, 101))

df = pd.DataFrame({'A': datos_1, 'B': datos_2})

df

df.head(6)

df.tail(9)

"""# Ejercicio 13

Agregar una nueva columna a un `DataFrame` con notación de slicing.

`df['nombre_nueva_columna'] = valores`


"""

nombre = ['Oliva', 'Daniela', 'Juan', 'Germán', 'Edward', 'Alex', 'Julio', 
          'Edgar', 'Angie', 'Irlesa']
puntaje = [11.5, 8, 15.5, np.nan, 8, 19, 13.5, np.nan, 8, 18]
intentos = [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
califico = ['Sí', 'No', 'Sí', 'No', 'No', 'Sí', 'Sí', 'No', 'No', 'Sí']

indices = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

jugadores = {'nombre': nombre, 'puntaje': puntaje, 'intentos': intentos, 
             'califico': califico}

df = pd.DataFrame(data=jugadores, index=indices)

df

#Valores nueva columna
colores = ['Negro', 'Blanco', 'Azul', 'Verde', 'Rojo', 'Amarillo', 
           'Gris', 'Naranja', 'Lila', 'Café']

df["Color"] = colores
df

"""# Recorrer un df

 Para iterar cada una de las filas de un `DataFrame` utilizamos la función `iterrows`.
 
 
"""

nombre = ['Oliva', 'Daniela', 'Juan', 'Germán', 'Edward', 'Alex', 'Julio', 
          'Edgar', 'Angie', 'Irlesa']
puntaje = [11.5, 8, 15.5, np.nan, 8, 19, 13.5, np.nan, 8, 18]
intentos = [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
califico = ['Sí', 'No', 'Sí', 'No', 'No', 'Sí', 'Sí', 'No', 'No', 'Sí']

indices = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

jugadores = {'nombre': nombre, 'puntaje': puntaje, 'intentos': intentos, 
             'califico': califico}

df = pd.DataFrame(data=jugadores, index=indices)

df

for indice, fila in df.iterrows():
    print(fila['nombre'], fila['califico'])

"""# Ejercicio 14 (Opcional)

Obtener como una lista Python los nombres de las columnas de un `DataFrame`.


"""

datos = {'X': [1, 2, 3, 4, 5], 'Y': [5, 4, 3, 2, 1], 'Z': [2, 3, 5, 7, 11]}

df = pd.DataFrame(datos)

df

"""# Ejercicio 15

Renombrar las columnas de un objeto `DataFrame` a partir del diccionario dado.


"""

datos = {'Columna1': [1, 2, 3, 4, 5], 'Columna2': [5, 4, 3, 2, 1], 
         'Columna3': [2, 3, 5, 7, 11]}

indices = ['a', 'b', 'c', 'd', 'e']

df = pd.DataFrame(data=datos, index=indices)

df

#Diccionario con los nuevos nombres de las columnas
renombrado_columnas = {'Columna1': 'X', 'Columna2': 'Y', 'Columna3': 'Z'}

"""# Ejercicio 16

* Guardar los registros de un `DataFrame` en un archivo de formato **CSV**.
* Prueba a descargarlos en tu PC.


"""

nombre = ['Oliva', 'Daniela', 'Juan', 'Germán', 'Edward', 'Alex', 'Julio', 
          'Edgar', 'Angie', 'Irlesa']
puntaje = [11.5, 8, 15.5, np.nan, 8, 19, 13.5, np.nan, 8, 18]
intentos = [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
califico = ['Sí', 'No', 'Sí', 'No', 'No', 'Sí', 'Sí', 'No', 'No', 'Sí']

indices = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

jugadores = {'nombre': nombre, 'puntaje': puntaje, 'intentos': intentos, 
             'califico': califico}

df = pd.DataFrame(data=jugadores, index=indices)

df

